### PR TITLE
Fixed FAQ accordion dropdown

### LINKED ISSUE #6: Switch FAQ section to dropdown menus
- [x] Change FAQs so that only questions show; clicking on them opens the answer
- [x] When you click on another question, any open questions should close
- [x] See 2022 website for example

### PR DESCRIPTION
**Pull request by aryasalian**
This resolves task #6 from the Projects tab. The 2022 website omitted the functionality of extracting text from the .JSON file and the 2021 website didn't have the dropdown functionality. I've merged both of these into one and switched the long Javascript code for the dropdown functionality written in the 2022 website with a shorter jQuery code instead.

### CODE REVIEW

File: static/js/main.js [hunk 1]
```diff
@@ -116,4 +117,14 @@ $(document).ready(function () {
             });
         });
     });
+
+    //functionality for FAQ accordion dropdown
+    $('#faq-container').on('click','.accordion-header', function() {   //selecting #faq-container here since its a parent static element, click() has issues working with dynamic elements
+        //console.log("clicked!");
```
Comment (atoneyd) [inline static/js/main.js]: remove the console.log

File: index.html [hunk 2]
```diff
@@ -102,7 +103,7 @@ <h2>I'm interested in being a...</h2>
                     <h1 class="tagline">HackNC 2023</h1>
                     <h2 class="date">October 27-29, 2023</h2>
                    <!-- <p class = "update"> Event Ended ...Stay tune for 2022 </p> -->
-                    
+                   
                     <!-- <button class="live-button hide-on-med-and-down"><a href="https://www.hacknc.com/live/">→ Event Live</a></button> -->
                     <!-- <button class="involve-button hide-on-med-and-down"><a href="https://forms.gle/cqkwFZum1BihNbpKA">2022 Hacker Interest form</a></button> -->
```
Comment (atoneyd) [inline index.html]: Can you actually remove this commented-out code from the previous PR? We don't need it for now and can always reference previous commits if we want to add it back in eventually

**Review by atoneyd — CHANGES_REQUESTED** [review]
This is great, thank you for commenting the code and giving context for the changes you made. Left some comments to clean up the code and requesting some small styling changes:

Could you make each question centered with the icon horizontally, and make it not wrap around the icon on a new line? See the FAQ section from https://fall2020.hacknc.com/ for an example of how it should look. I think we should reduce the spacing between each question as well.

**Comment by aryasalian** [comment]
> This is great, thank you for commenting the code and giving context for the changes you made. Left some comments to clean up the code and requesting some small styling changes:
> 
> Could you make each question centered with the icon horizontally, and make it not wrap around the icon on a new line? See the FAQ section from https://fall2020.hacknc.com/ for an example of how it should look. I think we should reduce the spacing between each question as well.

Sorted that out, how about now?

**Review by atoneyd — APPROVED** [review]
LGTM!

**Comment by aryasalian** [comment]
Great! Merging it.
